### ISSUE TITLE
firebase config?

### ISSUE THREAD

**Issue by simonmalessa** [antoni-berlin/checkin-app#1]
Hey There, 
First: Thanks for open sourcing this, I'd love to give it a try. 

Could you advise me where to enter the firebase configs? 

Cheers,
 Simon

**Comment by bogdanfer** [comment]
Hi @simonmalessa,
thanks for the interest! 

First you should open a (free) account here: https://firebase.google.com/
this article should give you some guidance on how to do that and where to get the config details. 

Once you have the config details, add them to this file: `src/components/MainComponent.vue` and line 118. 

Hope this helps!

**Comment by simonmalessa** [comment]
Awesome, thanks, working now :)
